### ISSUE TITLE
Warning Notice Install

### ISSUE THREAD

**Issue by mdestafadilah** [agumil/satusehat-sdk#2]
Halo pak, ini ss warningnya.

![13-08-2024 04-14-00](https://github.com/user-attachments/assets/ab351311-6c6c-4a22-9378-05ba3e58286b)

**Comment by agumil** [comment]
Terima kasih laporannya, sudah di-fix di commit [https://github.com/agumil/satusehat-sdk/commit/d8d549500525db21238e97855931280771f5d7d8](https://github.com/agumil/satusehat-sdk/commit/d8d549500525db21238e97855931280771f5d7d8) silahkan dicoba install/update kembali
